= Jordan Chong - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: My Team Manager (MTM)

---

== Overview

My Team Manager (MTM) is a desktop command-line interface (CLI) based address book application for football team managers.
It is a one-stop solution to help you manage your player’s contact details and team information in an efficient and convenient manner.
MTM is further enhanced with usability implementations that make MTM efficient and easy to use with JavaFX GUI display.


== Summary of contributions

* *Major enhancement*: added *team implementation and commands*.
** *What it does*: allows the user to perform *team management* functions such as creating, removing, renaming, viewing a team, and assigning players into a team.
** *Justification*: This feature is a core component to the product as it gives users the capability to manage and view their teams *easily and in a convenient way*.
** *Highlights*: The implementation requires new classes and commands to be created and also affects current existing `add` command. The class is set up so that future enhancements can use the data quickly. The implementation was challenging as it requires that player's information are in-sync with the information in the class.

* *Minor enhancement*: added a remark command that allows the user to leave a remark to a specific player. [https://github.com/CS2103JAN2018-F14-B1/main/pull/58[PR#58]]

* *Code contributed*: [https://github.com/CS2103JAN2018-F14-B1/main/blob/master/collated/functional/jordancjq.md[Functional code]] [https://github.com/CS2103JAN2018-F14-B1/main/blob/master/collated/test/jordancjq.md[Test code]]

* *Other contributions*:

** Project management:
*** Published releases `v1.3` ~ `v1.4` (2 release) on GitHub.
*** Documented issues of project using GitHub's _Issue Tracker_ and address the issues accordingly.
** Enhancements to existing features:
*** Enhanced functionality of `add` command that allows certain field to be optional. [https://github.com/CS2103JAN2018-F14-B1/main/pull/54[PR#54]]
*** Made changes based on suggestions from feedback. [https://github.com/CS2103JAN2018-F14-B1/main/pull/167[PR#167]]
** Documentation:
*** Update _About Us_ with team member's pictures and contributions. [https://github.com/CS2103JAN2018-F14-B1/main/pull/68[PR#68]][https://github.com/CS2103JAN2018-F14-B1/main/pull/49[PR#49]]
*** Re-arrange features in _User Guide_ into appropriate categories. [https://github.com/CS2103JAN2018-F14-B1/main/pull/110[PR#110]]
*** Update _User Guide_ on all *Team-Related* commands, and the following commands: +
`setmatch`, `nextmatch`, `remark`, `help`, `undo`, `redo`, and `select`.
*** Wrote the preface for the _Features_ segment in _User Guide_, *Getting started with Commands*, *The Use Of Alias*, and *Lookout for Tips, Notes, and Expected Outcomes*.
*** Create *Command Summary Table* in _User Guide_ for ease of viewing and quick access to commands.
*** Introduce the *Overview* segment into the _Developer Guide_.
*** Wrote the sections on *Remark a Player*, *Team-Related Enhancements*, and *Optional Field Add Command* in _Developer Guide_.
** Community:
*** PRs reviewed (with non-trivial review comments) [https://github.com/CS2103JAN2018-F14-B1/main/pull/57[PR#57]][https://github.com/CS2103JAN2018-F14-B1/main/pull/94[PR#94]][https://github.com/CS2103JAN2018-F14-B1/main/pull/171[PR#171]]
*** Reported bugs and suggestions for other teams in the class [https://github.com/CS2103JAN2018-F11-B4/main/issues/99[1],
https://github.com/CS2103JAN2018-F11-B4/main/issues/105[2],
https://github.com/CS2103JAN2018-F11-B4/main/issues/108[3],
https://github.com/CS2103JAN2018-F11-B4/main/issues/111[4],
https://github.com/CS2103JAN2018-F11-B4/main/issues/112[5],
https://github.com/CS2103JAN2018-F11-B4/main/issues/113[6]]


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=create]

include::../UserGuide.adoc[tag=assign]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=team]

